In [1]:
from collections import namedtuple
from recordclass import recordclass
import numpy as np

Point1 = namedtuple("Point1", "x y")
Point2 = recordclass("Point2", "x y")


named = Point1(2, 3)
record = Point2(2, 3)

arr = np.arange(30).reshape((5, 6))

print(arr[named])
print(arr[record])

15
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [3]:
arr[[2,3]]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [5]:
print(arr[tuple(named)])

15


In [1]:
from recordclass import dataobject

In [3]:
import numpy as np

In [13]:
class Point(dataobject):
    x:int
    y:int
    
    def __int__(self):
        return self.x, self.y


In [14]:
A=np.array([[1,2,3],[4,5,6]])

In [15]:
A[Point(0,0)]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices